# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=50)),
                ('value', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Critical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Asin')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=250)),
                ('bsr', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('bsr_link', models.TextField(default='')),
                ('review', models.IntegerField(default=0)),
                ('star', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('cart', models.NullBooleanField(default=True)),
                ('sell_yours', models.BooleanField(default=False)),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Asin')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.IntegerField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('use', models.IntegerField(default=0)),
                ('fail', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['use'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asin',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tag'),
        ),
        migrations.AddField(
            model_name='asin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
