# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_review_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='asin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Asin'),
        ),
    ]
